mysite/4_CSVの入力出力/file_uploader/file_uploader/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload_form.urls', namespace = 'upload_form')),
]

mysite/4_CSVの入力出力/file_uploader/upload_form/urls.py
from django.conf.urls import url
from upload_form import views

urlpatterns = [
    url(r'^$', views.form, name = 'form'),
    url(r'^complete/', views.complete, name = 'complete'),
]

mysite/4_CSVの入力出力/file_uploader/upload_form/models.py
from django.db import models

# Create your models here.
from django.db import models
from datetime import datetime

class FileNameModel(models.Model):
    file_name = models.CharField(max_length = 50)
    upload_time = models.DateTimeField(default = datetime.now)

mysite/4_CSVの入力出力/file_uploader/upload_form/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render, redirect
from django.template.context_processors import csrf
from django.conf import settings
from upload_form.models import FileNameModel
import sys, os
UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'

def form(request):
    if request.method != 'POST':
        return render(request, 'upload_form/form.html')

    file = request.FILES['file']
    path = os.path.join(UPLOADE_DIR, file.name)
    destination = open(path, 'wb')

    for chunk in file.chunks():
        destination.write(chunk)

    insert_data = FileNameModel(file_name = file.name)
    insert_data.save()

    return redirect('upload_form:complete')

def complete(request):
    return render(request, 'upload_form/complete.html')

mysite/4_CSVの入力出力/file_uploader/upload_form/templates/upload_form/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <title>FILEUPROAD</title>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>

mysite/4_CSVの入力出力/file_uploader/upload_form/templates/upload_form/complete.html
{% extends "upload_form/base.html" %}

{% block title %}FINISH{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">UPLOADFINISH</h1>
        <a href="{% url 'upload_form:form' %}"><button>RETURN</button></a>
    </div>
{% endblock content %}

mysite/4_CSVの入力出力/file_uploader/upload_form/templates/upload_form/form.html
{% extends "upload_form/base.html" %}

{% block title %}SUMPLE{% endblock title %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="file" name="file">
        <input type="submit" value="UPLOAD">
    </form>
{% endblock content %}